### ISSUE TITLE
Could you please release?

### ISSUE THREAD

**Issue by queeno** [census-ecosystem/opencensus-go-exporter-prometheus#19]
Hi there,

The last release of this repo was on 25th April 2019 and since then 7 commits have occurred to master.

It would be great if you could create a new GitHub release, so that we can take advantage of the great features added in the meanwhile (especially #8)

Thanks very much!

**NB:** Before opening a feature request against this repo, consider whether the feature should/could be implemented in exporter libraries in other languages. If so, please [open an issue on opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/issues/new) first.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by songy23** [comment]
V0.2.0: https://github.com/census-ecosystem/opencensus-go-exporter-prometheus/releases/tag/v0.2.0.

**Comment by queeno** [comment]
Thanks @songy23
