### ISSUE TITLE
Cut new release to upgrade statsd_exporter dependency

### ISSUE THREAD

**Issue by johanbrandhorst** [census-ecosystem/opencensus-go-exporter-prometheus#27]
### What version of the Exporter are you using?

v0.3.0

### What did you do?

Tried to run `go mod tidy` with a dependency on `contrib.go.opencensus.io/exporter/prometheus`.

### What did you expect to see?

Successful dependency resolution

### What did you see instead?

```
mypackage imports
        contrib.go.opencensus.io/exporter/prometheus imports
        github.com/prometheus/statsd_exporter/pkg/mapper imports
        github.com/prometheus/common/log: module github.com/prometheus/common@latest found (v0.30.0), but does not contain package github.com/prometheus/common/log
```

### Additional context
The `github.com/prometheus/common` module recently deprecated and removed the `github.com/prometheus/common/log` package in [v0.27.0](https://github.com/prometheus/common/releases/tag/v0.27.0). `github.com/prometheus/statsd_exporter` updated its dependency in [v0.21.0](https://github.com/prometheus/statsd_exporter/releases/tag/v0.21.0). The latest release of this module still depends on `github.com/prometheus/statsd_exporter` `v0.20.0` while `master` has been updated. A new release cut from `master` should fix the issue.

**Comment by johanbrandhorst** [comment]
CC @howardjohn from https://github.com/prometheus/common/issues/255#issuecomment-853929914

**Comment by howardjohn** [comment]
+1, ran into the same issue and had to hold back our dependency to a lower version for the time being.

**Comment by sagikazarmark** [comment]
Dependencies were updated in #25. A new release should solve the dependency issues, so +1!

**Comment by bufdev** [comment]
Any update on this? We'd really appreciate if it could get fixed, thanks!

**Comment by bogdandrutu** [comment]
Please do a new release :)

**Comment by punya** [comment]
Tagged [v0.4.0](https://github.com/census-ecosystem/opencensus-go-exporter-prometheus/releases/tag/v0.4.0).
